"""add EmailTemplate model for admin-editable email templates

Revision ID: 20d5d7a5b618
Revises: 1efcc6474e60
Create Date: 2025-05-25 14:10:20.658217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d5d7a5b618'
down_revision = '1efcc6474e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('subject', sa.String(length=200), nullable=False, server_default=''),
    #sa.Column('html_content', sa.Text(), nullable=False, server_default=''),
    sa.Column('subject', sa.String(length=200), nullable=False, server_default=''),
    sa.Column('html_content', sa.Text(), nullable=False, server_default=''),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.drop_table('email_template')
    # ### end Alembic commands ###
