"""Add hero_slide_interval to SiteSettings

Revision ID: c01cac1a2890
Revises: 20240528_add_hero_bg_image_and_slides_to_sitesettings
Create Date: 2025-05-28 18:53:25.856550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01cac1a2890'
down_revision = '20240528_add_hero_bg_image_and_slides_to_sitesettings'
branch_labels = None
depends_on = None


def upgrade():
    """Add hero_slide_interval to SiteSettings."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('site_settings', sa.Column('hero_slide_interval', sa.Integer(), nullable=True))
    # The following alter_column operations are not supported by SQLite, so we skip them for development
    # op.alter_column('site_settings', 'show_facebook',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('1'))
    # op.alter_column('site_settings', 'show_instagram',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('1'))
    # op.alter_column('site_settings', 'show_twitter',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The following alter_column operations are not supported by SQLite, so we skip them for development
    # op.alter_column('site_settings', 'show_twitter',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('1'))
    # op.alter_column('site_settings', 'show_instagram',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('1'))
    # op.alter_column('site_settings', 'show_facebook',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('1'))
    op.drop_column('site_settings', 'hero_slide_interval')
    # ### end Alembic commands ###
