"""Add featured_home and featured_order to Place

Revision ID: d7ee0eedc236
Revises: 20240527_add_email_to_testimonial
Create Date: 2025-05-27 21:32:09.794025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ee0eedc236'
down_revision = '20240527_add_email_to_testimonial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('featured_home', sa.Boolean(), nullable=True))
    op.add_column('place', sa.Column('featured_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'featured_order')
    op.drop_column('place', 'featured_home')
    # ### end Alembic commands ###
